spring:
  application:
    name: tc1-api-phto
  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATA_SOURCE_URL}
    username: ${SPRING_DATA_SOURCE_USERNAME}
    password: ${SPRING_DATA_SOURCE_PASSWORD}
    jpa:
      generate-ddl: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
server:
  port: ${SERVER_PORT}
