spring:
  application:
    name: tc1-api-phto
  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    url: jdbc:postgresql://localhost:5432/db_tc1
    username: admin
    password: admin
  jpa:
    show-sql: true
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
server:
  port: 8080

